# Generated by Django 4.2.7 on 2023-11-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_privacypolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("contact_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=15)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                ("admin_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact Request",
                "verbose_name_plural": "Contact Requests",
                "ordering": ["-contact_date"],
            },
        ),
    ]
