# Generated by Django 4.2.7 on 2024-01-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
