# Generated by Django 4.2.7 on 2024-01-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auditlogconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=100)),
                ("profile_url", models.URLField()),
                ("image", models.ImageField(upload_to="social_media_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
